language: java
jdk: oraclejdk8
branches:
  except:
  - "/^*-v[0-9]/"
  - "maven-repo"
env:
  global:
    - MC_VERSION=1.11.2
    - PLUGIN_VERSION=2.0
install: true
before_script:
- 'sed -i "s/^\(version: \).*\$/\1$PLUGIN_VERSION.$TRAVIS_BUILD_NUMBER-mc$MC_VERSION/g" src/main/resources/plugin.yml'
script: gradle build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_deploy:
- cp build/libs/NyaaCore.jar ./NyaaCore-$PLUGIN_VERSION.$TRAVIS_BUILD_NUMBER-mc$MC_VERSION.jar
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$PLUGIN_VERSION.$TRAVIS_BUILD_NUMBER-mc$MC_VERSION
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://RecursiveG:$GITHUB_OAUTH_TOKEN@github.com/NyaaCat/NyaaCore --follow-tags
deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true
  api_key: $GITHUB_OAUTH_TOKEN
  file: ./NyaaCore-$PLUGIN_VERSION.$TRAVIS_BUILD_NUMBER-mc$MC_VERSION.jar
  on:
    tags: true
    all_branches: true
