language: "en_US"
enchantSrc: {}
enchant:
  PROTECTION_ENVIRONMENTAL:
    MaxLevel: 4
  PROTECTION_FIRE:
    MaxLevel: 4
  PROTECTION_FALL:
    MaxLevel: 4
  PROTECTION_EXPLOSIONS:
    MaxLevel: 4
  PROTECTION_PROJECTILE:
    MaxLevel: 4
  OXYGEN:
    MaxLevel: 3
  WATER_WORKER:
    MaxLevel: 1
  MENDING:
    MaxLevel: 1
  THORNS:
    MaxLevel: 3
  DEPTH_STRIDER:
    MaxLevel: 3
  FROST_WALKER:
    MaxLevel: 2
  DAMAGE_ALL:
    MaxLevel: 5
  DAMAGE_UNDEAD:
    MaxLevel: 5
  DAMAGE_ARTHROPODS:
    MaxLevel: 5
  KNOCKBACK:
    MaxLevel: 2
  FIRE_ASPECT:
    MaxLevel: 2
  LOOT_BONUS_MOBS:
    MaxLevel: 3
  DIG_SPEED:
    MaxLevel: 5
  SILK_TOUCH:
    MaxLevel: 1
  DURABILITY:
    MaxLevel: 3
  LOOT_BONUS_BLOCKS:
    MaxLevel: 3
  ARROW_DAMAGE:
    MaxLevel: 5
  ARROW_KNOCKBACK:
    MaxLevel: 2
  ARROW_FIRE:
    MaxLevel: 1
  ARROW_INFINITE:
    MaxLevel: 1
  LUCK:
    MaxLevel: 3
  LURE:
    MaxLevel: 3

